// Code generated by "stringer -type=TimeUnit"; DO NOT EDIT.

package badgers

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Nanoseconds-0]
	_ = x[Microseconds-1]
	_ = x[Milliseconds-2]
}

const _TimeUnit_name = "NanosecondsMicrosecondsMilliseconds"

var _TimeUnit_index = [...]uint8{0, 11, 23, 35}

func (i TimeUnit) String() string {
	if i < 0 || i >= TimeUnit(len(_TimeUnit_index)-1) {
		return "TimeUnit(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TimeUnit_name[_TimeUnit_index[i]:_TimeUnit_index[i+1]]
}
